project:
  type: website

website:
  title: "Heath Yates"
  description: "Personal Blog of Heath Yates"
  site-url: https://www.heathyates.com
  navbar:
    right:
      - about.qmd
      - text: "Resume"
        href: resume/yates-resume-cv.pdf
      - icon: github
        href: https://github.com/heathyates
      - text: "{{< iconify fa6-brands bluesky >}}"  
        href: https://bsky.app/profile/heathyates.bsky.social
      

format:
  html:
    theme: 
      - cosmo
      - style.scss
    include-after-body: _footer.html



