version: '3.8'

services:
  app:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/workspace
      - ~/.ssh:/root/.ssh
    command: quarto preview --host 0.0.0.0 --port 4000 --no-browser
